### ISSUE TITLE
Could not update record for example.com, required DNS record ID missing

### ISSUE THREAD

**Issue by toralux** [justmiles/traefik-cloudflare-tunnel#7]
If I add a `traefik.yml `with router that should forward traffic to a loadbalancer and not be tunneled.

```
http:
  routers:
    myrouter:
      rule: "Host(`example.com`)"
      entryPoints: ["web"]
      service: myservice

  services:
    myservice:
      loadBalancer:
        servers:
          - url: "https://10.0.0.123"
```

... I get this error ...

```
traefik-cloudflare-tunnel-whoami  | time="2025-02-15T00:26:26Z" level=fatal msg="could not update record for example.com, required DNS record ID missing"
```

Error message could be find in library [cloudflare-go](https://pkg.go.dev/github.com/cloudflare/cloudflare-go)

If I remove the router and service from `traefik.yml` it works and I guess `trafik-cloudflare-tunnel` tries to setup a tunnel for every route that has entrypoint `web`. Is it possible to exclude routes from being tunneled? E.g. by adding a label on myrouter so it will not be picked up by `trafik-cloudflare-tunnel`? Or just skip routers that forward to external loadbalancers / services (that is not in Docker Compose)?
